# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(default='introduction', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
