# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_faqpage_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subheading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
