# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 03:57
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='portfolios',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='portfolios', to='home.ProjectPage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='services', to='home.ProjectPage'),
        ),
    ]
