# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170414_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpageblock',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='clientpageplacements',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientpageplacements',
            name='clientblock',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='clientblock',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='clientblock',
        ),
        migrations.DeleteModel(
            name='ClientPageBlock',
        ),
        migrations.DeleteModel(
            name='ClientPagePlacements',
        ),
    ]
