# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 03:59
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170409_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='portfolios',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_portfolios', to='home.ProjectPage'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='project_services', to='home.ProjectPage'),
        ),
    ]
