# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('home', '0009_portfoliopage_servicepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliopage',
            name='homepage_portfolio',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='portfoliopage',
            name='projectpage',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='homepage_service',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='projectpage',
        ),
        migrations.DeleteModel(
            name='PortfolioPage',
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
    ]
