# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_portfolioindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.PortfolioIndexPage'),
        ),
    ]
